# Usar una imagen base de Python
FROM python:3.11.9

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de requisitos a la imagen
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

# Exponer el puerto que usará FastAPI
EXPOSE 8001

# Comando para ejecutar el servidor de Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
